import {createAction} from 'redux-actions';

export default {
    'SETTINGS/SHOW_SETTINGS': createAction('SETTINGS/SHOW_SETTINGS'),
    'SETTINGS/HIDE_SETTINGS': createAction('SETTINGS/HIDE_SETTINGS'),

    'SETTINGS/GET_SETTINGS': createAction('SETTINGS/GET_SETTINGS'),
    'SETTINGS/GET_SETTINGS_SUCCESSFULLY': createAction('SETTINGS/GET_SETTINGS_SUCCESSFULLY'),
    'SETTINGS/GET_SETTINGS_ERROR': createAction('SETTINGS/GET_SETTINGS_ERROR'),
    'SETTINGS/SAVE_SETTINGS': createAction('SETTINGS/SAVE_SETTINGS'),
    'SETTINGS/SAVE_SETTINGS_SUCCESSFULLY': createAction('SETTINGS/SAVE_SETTINGS_SUCCESSFULLY'),
    'SETTINGS/SAVE_SETTINGS_ERROR': createAction('SETTINGS/SAVE_SETTINGS_ERROR'),
};