import {createAction} from 'redux-actions';

export default {
    'TOP_RESULTS/SHOW_TOP_RESULTS': createAction('TOP_RESULTS/SHOW_TOP_RESULTS'),
    'TOP_RESULTS/HIDE_TOP_RESULTS': createAction('TOP_RESULTS/HIDE_TOP_RESULTS'),

    'TOP_RESULTS/PLAYER_NAME_CHANGED': createAction('TOP_RESULTS/PLAYER_NAME_CHANGED'),
    'TOP_RESULTS/GET_RESULTS': createAction('TOP_RESULTS/GET_RESULTS'),
    'TOP_RESULTS/GET_RESULTS_SUCCESSFULLY': createAction('TOP_RESULTS/GET_RESULTS_SUCCESSFULLY'),
    'TOP_RESULTS/GET_RESULTS_ERROR': createAction('TOP_RESULTS/GET_RESULTS_ERROR'),
    'TOP_RESULTS/SAVE_RESULT': createAction('TOP_RESULTS/SAVE_RESULT'),
    'TOP_RESULTS/SAVE_RESULT_SUCCESSFULLY': createAction('TOP_RESULTS/SAVE_RESULT_SUCCESSFULLY'),
    'TOP_RESULTS/SAVE_RESULT_ERROR': createAction('TOP_RESULTS/SAVE_RESULT_ERROR'),
    'TOP_RESULTS/PLAYER_NAME_ERROR': createAction('TOP_RESULTS/PLAYER_NAME_ERROR'),
};